### ISSUE TITLE
Airport not found in optd_por_public.csv

### ISSUE THREAD

**Issue by pierrelesesvre** [opentraveldata/geobases#22]
Hello,

I am using GeoBases on MIDT data (flights bookings), and I found that the following IATA codes do not exist in optd_por_public.csv:
DTZ, BYZ, GIJ, HFH

I am not sure whether they really exists or whether they are just false data.

Can you update this .csv file, if needed?

Best regards,
Pierre

**Comment by da115115** [comment]
Only DTZ is a valid IATA code, which has indeed recently been assigned to the Dortmund railway station.
The other three codes are not valid, and have not been for at least the last five years.
DTZ is not in Geonames right now. Do not hesitate to add it.

**Comment by chmduquesne** [comment]
To me, DTZ looks more like a real estate agent company which happens to be
hosted in LGG airport.

**Comment by chmduquesne** [comment]
Sorry, I wrote that from my mail client, before I received Denis' answer. I did not mean to contradict his statement. You should read what I wrote as an explanation to to why you thought DTZ was the IATA code for Liège.

**Comment by da115115** [comment]
The Dortmund railway station has been added within Geonames: http://www.geonames.org/11101852
