### ISSUE TITLE
I can't install this modules. It prints the following message when i try to install it:

### ISSUE THREAD

**Issue by TheBugYouCantFix** [opentraveldata/geobases#27]
C:\Users\alexg>pip install GeoBases
Collecting GeoBases
  Using cached https://files.pythonhosted.org/packages/26/4a/099b2e360e9419b14121b5b549a678ac7a56690ac29e195810bc8bbb0ef5/GeoBases-5.0.16.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\alexg\appdata\local\programs\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\alexg\\AppData\\Local\\Temp\\pip-install-q2dg3obe\\GeoBases\\setup.py'"'"'; __file__='"'"'C:\\Users\\alexg\\AppData\\Local\\Temp\\pip-install-q2dg3obe\\GeoBases\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\alexg\AppData\Local\Temp\pip-install-q2dg3obe\GeoBases\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\alexg\AppData\Local\Temp\pip-install-q2dg3obe\GeoBases\setup.py", line 49, in <module>
        print >> stderr, '/!\ Installing without "%s"' % \
    TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'. Did you mean "print(<message>, file=<output_stream>)"?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by alexprengere** [comment]
The `GeoBases` package is only compatible with Python2. For Python3, you can use [GeoBases3K](https://pypi.org/project/GeoBases3K).

Please note that GeoBases is no longer maintained. If you only rely on the Python API on top of opentraveldata, I suggest you use [NeoBase](https://pypi.org/project/NeoBase/) instead.
