### ISSUE TITLE
I can't run "GeoBase(data='ori_por', verbose=False)" with the error message

### ISSUE THREAD

**Issue by sillykim** [opentraveldata/geobases#28]
Based on the closed issue (I can't install this module... on July 17,2020), I have installed GeoBases3K as I am using Python version 3. I think that the installation process was successfully done because 1) I have not seen any errors during pip install, 2) I can import "from GeoBases import GeoBase", and 3) I can run "GeoBase(data='stations', verbose=False). All these things considered, I am assuming that the installation was successfully completed. However, when I try to run "GeoBase(data='ori_por', verbose=False)", it always gives me an error message saying 'charmap' codec can't decode byte 0x90 in position 728: character maps to <undefined>. 

I have tried to install it from GitHub instead of pip install; but it does not change anything. If you can help me shoot this issue, I will be appreciated.

**Comment by da115115** [comment]
Thanks Andy!

From what I understand from @alexprengere , GeoBase is no longer maintained. It is recommended to switch to NeoBase: https://pypi.org/project/NeoBase/

Also, if you are interested to have a Python wrapper around Open Travel Data (OPTD), you can use https://github.com/opentraveldata/python-opentraveldata (on PyPi: https://pypi.org/project/opentraveldata/)

Note that `ori_por` is the former name of `optd_por`, meaning the Open Travel Data (OPTD) points of reference (POR). The corresponding data files are:
* [`optd_por_public.csv`](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_public.csv) for the POR having a IATA code
* [`optd_por_public_all.csv`](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_public_all.csv) for all the POR having any code type among IATA, ICAO, UIC, UN/LOCODE

**Comment by alexprengere** [comment]
Indeed GeoBases is no longer maintained and should be archived. If you need a Python API on top of the great [optd_por_public](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_public.csv) file, I maintain a much smaller project called [NeoBase](https://pypi.org/project/NeoBase/), that is better suited to manipulate that data. It follows the same API as GeoBases, but contains code that is custom to OpenTravelData, like dropping point of references that are no longer valid, letting you chose a reference data when loading the data (whereas GeoBases wanted to be very generic over multiple data sources). If you have the same problem on NeoBase, you can open issue on the bug tracker.

@denisarnaud are you still maintaining the optd files? And thanks for the python-opentraveldata API, I will check it out.

**Comment by da115115** [comment]
Yes, @alexprengere , I still maintain OPTD data files, but with a much lower frequency than before, as I no longer have access to the IATA reference data files. If you or Andy have access to them, you can contact me in private (and/or you can help me maintain that part of OPTD).
By the way, IATA seems to share the list of POR on [their search page](https://www.iata.org/en/publications/directories/code-search/): look at the bottom of the page. A web page scraper tool could extract the data from there (most probably, some throttling capability would be required).
