### ISSUE TITLE
Paramétrer la largeur des cercles sur la carte

### ISSUE THREAD

**Issue by nicolas-75** [opentraveldata/geobases#8]
Bonjour,

Il est possible de visualiser des cercles sur la carte à l'aide d'une valeur page_rank

Cependant, je n'arrive pas à ce que le diamètre du cercle soit fixe. Actuellement, la taille dépend du niveau de zoom.

Pouvez-vous me dire comment faire ?

Merci

**Comment by alexprengere** [comment]
Bonjour,

Effectivement, la taille des cercles est calculée pour s'ajuster en fonction du niveau de zoom, de façon à ce que l'affichage soit toujours "pertinent". En pratique, l'aire du plus grand cercle est fixée à un certain pourcentage de la taille de la carte vue par l'utilisateur (par exemple 15%), et les aires des autres cercles sont ajustées en conséquence.

Pour l'instant, il n'est pas possible de faire en sorte que la taille des cercles soit fixes, mais il est possible de contrôler la taille des cercles dans leur ensemble via le _slider_ en haut de la page.

Il serait simple de rajouter une _checkbox_ afin de pouvoir dire "fixer la taille des cercles" en haut. Est-ce que cela serait vraiment utile dans votre cas, ou l'utilisation du slider pour ajuster la taille des cercles est suffisante ?

**Comment by nicolas-75** [comment]
Bonjour,

Je n'avais pas vu qu'il y avait la possibilité de modifier la taille des cercles, c'est très bien. Geobase semble orienté analyse plutôt que restitution alors je vais continuer à utiliser un autre logiciel pour arriver au résultat attendu mais il est prometteur.

Avez vous pour objectif de compléter la visualisation des données : diagrammes, histogrammes, ... Par exemple pour arriver à ces résultats : https://www.e-education.psu.edu/natureofgeoinfo/c3_p17.html

Merci !

**Comment by alexprengere** [comment]
Effectivement ce projet a plusieurs objectifs, entre autres:
- effectuer des requêtes complexes de façon simple, en Python ou en ligne de commande
- visualiser ou exporter le résultats de ces requêtes
- fournir des jeux de données par défaut

Pour l'instant, peu de visualisations sont disponibles (surtout cartes et terminal), et nous nous concentrons sur ce qui n'est pas évident à obtenir rapidement via des outils classiques. Par exemple `awk`, `sort`, `uniq` (sous Linux) viennent facilement à bout de beaucoup de problèmes simples de comptage dans les fichiers.

Par exemple voici comment obtenir simplement l'équivalent d'un histogramme sur une colonne d'un fichier csv:

``` shell
$ cat file.csv
A,B,other,things
A,C,other,things
B,D,other,things
$ cat file.csv | awk -F','  '{ print $1 }' | sort | uniq -c | sort -nr
      2 A
      1 B
```

Du coup il n'est pas forcément très utile de fournir de type de visualisation (dans un premier temps).
Récemment une visualisation de type graphe a été rajoutée (encore en beta), plus d'explications ici: #7.
Merci du retour en tout cas!
